name: Update Anime Rankings Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run ETL Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python backend/etl.py
